name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: CMake build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./build.bat
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: DarkCave
        path: build/Debug/DarkCave.exe

  release:
      needs: build
      runs-on: ubuntu-latest
      name: Release game
      steps:
      - name: Download exe
        uses: actions/download-artifact@v3
        with:
          name: DarkCave
        # https://github.com/ncipollo/release-action
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: v${{ github.event.inputs.version }}
          artifacts: DarkCave.exe