name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0.0'

jobs:
  build-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: CMake build
      run: make build
      # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: v${{ github.event.inputs.version }}
        artifacts: build/Debug/DarkCave.exe